# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:16
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from roles.models import AgentNoun, Homonym


def load_fixture(apps, schema_editor):
    # NB word_data.json file generated by import_* management scripts
    call_command('loaddata', 'word_data.json', app_label='roles')


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries..."

    AgentNoun.objects.all().delete()
    Homonym.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
